#!/bin/bash

CONF_VAL=`git config --get hooks.tests`

if [ $? != 0 ]; then
    echo "WARNING: hooks.tests not defined in your git config settings."
    CONF_VAL="never"
fi

if [ "$CONF_VAL" == "never" ]; then
    exit 0
else
    ROOT=`git rev-parse --show-toplevel`
    cd $ROOT
    python3 -m unittest discover ./tests/
fi
